name: Deployment

on: push

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: graphql-api
      url: https://graphql-api-nc2w.onrender.com
    steps:
      - uses: actions/checkout@v3